### ISSUE TITLE
Loading View Data keeps spinning.

### ISSUE THREAD

**Issue by MKobbero** [amoerie/teamcity-theatre#23]
Hi

I am afraid i cant give you much debug info.
I have setup the project as described in installation guide, and it does manage to connect to the teamcity server and show the settings view (though rather slowly). I have then added a single tile and tries to view the dashboard, but the "Loading view data" just keeps spinning.

**Comment by MKobbero** [comment]
After a closer look, my issue seems similar to: #21

**Comment by amoerie** [comment]
Since the settings seem to work, your application pool must have proper access to the file you configured for the configuration.json file.

Is it an option for you to clone the repository and just start the project in debug mode from Visual Studio? What you would have to do is:

1. Ensure you have VS 2017 + .NET Core SDK 1.1 or higher
2. Ensure you have Yarn installed
3. Build the frontend by executing "yarn run build:release" from the src/TeamCityTheatre.Web folder OR run the "publish.cmd" file
4. Copy the settings from your deployed appsettings.json to the appsettings.json file in the solution. 
5. Put a breakpoint in TeamCityTheatre.Web.Controllers.ViewDataController#18 and take it from there.

In any case, my next release will contain logging!!

**Comment by captainjono** [comment]
Seems TeamCity keeps breaking their rest API. There is no mention on this page also what API version the current build of TeamCityTheatre is built against (my guess its >10.0).

This constant spinning is a symptom of a failure to get the build info. Im running against TC 9.1 and i had to modify 
```
BuildDataService.GetBuildsOfBuildConfigurationAsync(..) {
var request = new RestRequest("builds/?locator=branch:(default:any" <- change this to suit ur TC version
}
```
against TC9.1 i had to change remove ",policy:active_history_and_active_vcs_branches" from the query

each case is going to be different im guessing.
here is a debugging dll if u want to quickly know why ur failure is
http://s000.tinyupload.com/index.php?file_id=09641629632736028402

copy this to the website root, and then at the console run: 
```
dotnet TeamCityTheatre.Web.dll
```
this will spinup a webserver
hit to the dashboard after u have added some tiles
the console will print out the API response / error response.

i simply added an interceptor to the restSharp via 
```
TeamCityRequestPreparer.Prepare()... {
request.OnBeforeDeserialization = (resp) =>
            {
                Console.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
                Console.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
                Console.WriteLine(resp.Content);
                Console.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
                Console.WriteLine(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
            };
}
```

**Comment by amoerie** [comment]
The next release (3.0) will contain Serilog logging to facilitate these kinds of problems.
I've also added a note that says TeamCityTheatre is compatible with 2017.1.4, other versions may or may not work. (I have no way to test this)
