### ISSUE TITLE
TeamCity Theatre projects does not update anymore 

### ISSUE THREAD

**Issue by gordonAndersen** [amoerie/teamcity-theatre#25]
Updated TeamCity to 2017.2.3 (build 51047)
After the release all project we have specified in the TeamCity Theatre (TCT) configuration are "stock". Meaning the do not update or monitor new builds.

![image](https://user-images.githubusercontent.com/14275249/38689324-9c58efea-3e7b-11e8-8f27-e01791ac41db.png)

Tried to go through the logs but nothing seems to indicate an error? Is there a cache or something that need to be cleared?

**Comment by amoerie** [comment]
Nope, no caching involved. For now you could try to launch the project from VS with a debugger. In the next release, which I'll try put out shortly, I'll add a bunch more logging for issues like this.

Here at work we're still on 2017.1.4 so I cannot reproduce your problem just yet.

**Comment by Sharken03** [comment]
The problem is due to not having a BranchSpecification when using Mercurial as VCS Root. 
In the attached screenshot there was a BranchSpecification present up until build #172, and then it was removed as it was enough to have a Default branch.

A workaround is to add the same Default branch as a BranchSpecification on the form +:<defaultbranch>

![missingbranch](https://user-images.githubusercontent.com/37798154/38936111-62f5537a-4320-11e8-9982-df69ad8d8044.png)

**Comment by amoerie** [comment]
Added logging to make finding these problems easier. Glad to hear you found a solution!
