### ISSUE TITLE
Default to view, load specific view from url?

### ISSUE THREAD

**Issue by andrewdj** [amoerie/teamcity-theatre#27]
it would be great if hitting http://localhost/tctheatre/dashboard could load the first view if there's only one set up or, ability to hit http://localhost/tctheatre/dashboard?id=[guid] to load the view directly.

Is the latter already possible?

**Comment by amoerie** [comment]
Not possible right now, but should be doable! I'll try to take it along in the next release.

If you want to have a stab yourself, you would have to start from the TeamCityTheatre.Web/Views/home/dashboard.tsx, read the id or name from the URL somehow, and then call the 'selectView' function with the correct object. The full list of views is already there. 

I would guess reading the URL will be the trickiest part, and you'd also maybe have to convince MVC to return the same view for any URL that begins with /dashboard.

In any case, you don't have to do any of this, unless you're not very patient. ;-)

**Comment by amoerie** [comment]
I anticipate somewhere this week 😃

**Comment by amoerie** [comment]
3.0 will contain:

- When only one view is defined, that view is loaded immediately
- You can navigate to a single view by just opening /teamcitytheatre/dashboard/my-view-name.
 The buttons on the view switching screen have been modified to also just point to those URLs, instead of loading the view in javascript.
