### ISSUE TITLE
Filter by branch?

### ISSUE THREAD

**Issue by andrewdj** [amoerie/teamcity-theatre#32]
It would be good if you could specify a branch filter pattern under settings, e.g. you might only want to show master builds, or master and develop branches, but not individual feature branches.

**Comment by andrewdj** [comment]
On further investigation, having tried to enable 8 branches in tctheatre, it's still not showing our "master" branch which hasn't been built for 4 days, with 5 more active branches ahead of it, so I guess teamcity itself may not be returning the master branch as an "active" branch?

**Comment by amoerie** [comment]
For each build configuration id, it fetches the last 100 builds and then groups them by branch name, recognizing if the default branch is present.

If the default branch hasn't been built for a long time, and more than 100 builds have passed on other branches, then indeed you will no longer see it.

This is by design I'm afraid. 

How would this build filter work then? It'd have to compatible with one of the branch locators, as described in https://confluence.jetbrains.com/display/TCD10/REST+API#RESTAPI-BuildLocator.

**Comment by andrewdj** [comment]
It doesn't actually look possible on further investigation, as the branch locator doesn't appear to accept wildcards or regular expressions, which I had assumed might be possible.

I had also wondered if the filter could apply AFTER the request to TC was made, by looking at the branchName attribute when grouping them, but this will suffer from the same problem you've stated if not re-built recently.

I've temporarily resolved my specific use case by modifying the branch locator  in the code to only return the default branch. It's not ideal, but perhaps ability to have a "Only default builds?" checkbox in settings that changes default:any to default:true in the branch locator? 

(Or making the entire branch locator something you can configure rather than have to hard-code and recompile?)

The use case for this is that I've worked in quite a few places where we're not too fussed about feature branches failing, but the build dashboard and lights are linked to the default branch.

I've not used React before, but if it's something you think might be okay to include, I could have a go at making the change and submitting a PR, if I have time.

**Comment by amoerie** [comment]
Yes, that's what I was afraid of.. and doing the filtering on our side will indeed not be waterproof.

Your use case seems valid, and I think it should be quite doable. Since the requests are fired off for each tile, wouldn't it make most sense if this was configurable per tile? (And not per view).

If you want to have a go, be my guest. 😄 Since this all started out as a little experimental pet project of mine, the technology is quite unconventional I'm afraid: React + RxJs. 

I can take a stab at it too if you want.

**Comment by amoerie** [comment]
In 3.1.0 this setting will be configurable from appsettings.json, more specifically you will be able to specify the entire build locator URL.

**Comment by Sharken03** [comment]
@amoerie Would it be possible to expand on this by defining branches for each tile (build configuration) within a view ?

**Comment by amoerie** [comment]
@Sharken03 Could you open a new issue please? That would facilitate the discussion. Please elaborate on your use case and why this would be useful to you, thanks!

And if you want to take a stab at it yourself, I'm always willing to help with PRs!

**Comment by Sharken03** [comment]
Added issue #133 for the feature.
